services:
  webreader:
    image: webreader
    ports:
      - "${PORT_1_1}:${PORT_1_2}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    restart: always
    depends_on:
      - db
      - minio
  
  db:
    image: postgres:16-alpine
    env_file:
      - ../.env_pg
    ports:
      - "${PORT_1_1}:${PORT_1_2}"
    restart: always
  
  minio:
    image: minio/minio:latest
    ports:
      - "${PORT_1_1}:${ORT_1_2}"
      - "${PORT_2_1}:${PORT_2_2}"
    env_file:
      - ../.env_s3
    command: server /data --console-address ":9001"
    restart: always
  
  minio-create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo 'Creating default buckets...' &&
        /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin &&
        /usr/bin/mc mb local/mybucket &&
        echo 'Buckets created successfully!'
      "
