services:
  webreader:
    image: webreader
    ports:
      - "${PORT_1_1}:${PORT_1_2}"
      - "${PORT_2_1}:${PORT_2_2}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    restart: always
    volumes:
      - ${CHAIN}:/https/fullchain.pem:ro
      - ${PRIVATE_KEY}:/https/privkey.pem:ro
    entrypoint: >
      sh -c "
      echo 'Генерация PFX сертификата...' &&
      openssl pkcs12 -export -out /https/cert.pfx -inkey /https/privkey.pem -in /https/fullchain.pem -passout pass:${CERT_PASSWORD} &&
      echo 'Сертификат успешно создан, запуск приложения...' &&
      exec dotnet webreader.dll
      "
    depends_on:
      - db
      - minio
    networks:
      - webreader_network
    user: root

  db:
    image: postgres:16-alpine
    env_file:
      - ../.env_pg
    ports:
      - "${DB_PORT_1_1}:${DB_PORT_1_2}"
    restart: always
    networks:
      - webreader_network

  minio:
    image: minio/minio:latest
    ports:
      - "${S3_PORT_1_1}:${S3_PORT_1_2}"
      - "${S3_PORT_2_1}:${S3_PORT_2_2}"
    env_file:
      - ../.env_s3
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - webreader_network

  minio-create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo 'Creating default buckets...' &&
        /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin &&
        /usr/bin/mc mb local/mybucket &&
        echo 'Buckets created successfully!'
      "
    networks:
      - webreader_network

networks:
  webreader_network:
    driver: bridge
