name: Deploy Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run on'
        required: true
        default: "master"
        type: string

jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Pulling latest changes from master...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: /${{ secrets.SERVER_USER }}/Projects/deploy_git_reset.sh

  stopping:
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: Stopping container...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: /${{ secrets.SERVER_USER }}/Projects/deploy_stop.sh

  starting:
    runs-on: ubuntu-22.04
    needs: stopping
    steps:
      - name: Building and starting new container...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: /${{ secrets.SERVER_USER }}/Projects/deploy_start.sh

  pruning:
    runs-on: ubuntu-22.04
    needs: starting
    steps:
      - name: Pruning Docker system...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: /${{ secrets.SERVER_USER }}/Projects/deploy_prune.sh

  restarting:
    runs-on: ubuntu-22.04
    needs: pruning
    steps:
      - name: Restarting Docker system...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: /${{ secrets.SERVER_USER }}/Projects/deploy_restart.sh
